
export const vendors = [
    {
        ID: 1,
        NAME: 'Rajdoot',
    },
    {
        ID: 2,
        NAME: 'Shripad',
    },
    {
        ID: 3,
        NAME: 'Shubham',
    },
];
export const visitors = [
    {
        ID: 1,
        NAME: 'SK Photographers',
        EMAIL_ID: 'skuser@gmail.com',
        COMPANY_NAME: 'SK Photographers',
        COUNTRY: 'India',
        CITY: 'Sangli',
        DESIGNATION: 'Photographer',
        ACTIVE: true,
        MOBILE_NO: 9898989898,
        CODE: '+91',
    },
    {
        ID: 2,
        NAME: 'PK Photographers',
        EMAIL_ID: 'pkuser@gmail.com',
        COMPANY_NAME: 'PK Photographers',
        COUNTRY: 'India',
        CITY: 'Sangli',
        DESIGNATION: 'Photographer',
        ACTIVE: true,
        MOBILE_NO: 9898989898,
        CODE: '+91',
    },
    {
        ID: 3,
        NAME: 'Mr. XYZ',
        EMAIL_ID: 'xyz@gmail.com',
        COMPANY_NAME: 'X Industry',
        COUNTRY: 'India',
        CITY: 'Sangli',
        DESIGNATION: 'MD',
        ACTIVE: true,
        MOBILE_NO: 9898989898,
        CODE: '+91',
    },

    {
        ID: 4,
        NAME: 'Mr. AAXYZ',
        EMAIL_ID: 'sad@gmail.com',
        COMPANY_NAME: 'terryye Industry',
        COUNTRY: 'India',
        CITY: 'Sangli',
        DESIGNATION: 'MD',
        ACTIVE: true,
        MOBILE_NO: 9898989898,
        CODE: '+91',
    },
    {
        ID: 5,
        NAME: 'Mr. GGGXYZ',
        EMAIL_ID: 'ahtj@gmail.com',
        COMPANY_NAME: 'Xee Industry',
        COUNTRY: 'India',
        CITY: 'Sangli',
        DESIGNATION: 'MD',
        ACTIVE: true,
        MOBILE_NO: 9898989898,
        CODE: '+91',
    },
    
    
];

export const visits = [
    {
        ID: 1,
        NAME: 'SK Photographers',
        PURPOSE_OF_VISIT: 'Capmia Mens Chronograph Watch 44mm 5 ATM',
        MEETING_WITH_ID: 1,
        MEETING_WITH_NAME: 'ABC',
        DATE_OF_VISIT: '04-04-2023',
        DURATION_OF_VISIT: '02hrs 30m',
        DURATION_HRS: 3,
        DURATION_MINUTES: 0,
        COMPANY_NAME: 'SK Photographers',
        COUNTRY: 'India',
        CITY: 'Sangli',
        PROFESSION: 'Photographer',
        ACTIVE: true,
        VISITOR_ID: 3,
    },
    {
        ID: 2,
        NAME: 'PK Photographers',
        PURPOSE_OF_VISIT: 'Capmia Mens Chronograph Watch 44mm 5 ATM',
        MEETING_WITH_ID: 2,
        MEETING_WITH_NAME: 'ABC',
        DATE_OF_VISIT: '05-04-2023',
        DURATION_OF_VISIT: '01hrs 00m',
        DURATION_HRS: 1,
        DURATION_MINUTES: 25,
        COMPANY_NAME: 'PK Photographers',
        COUNTRY: 'India',
        CITY: 'Sangli',
        PROFESSION: 'Photographer',
        ACTIVE: true,
        VISITOR_ID: 3,
    },
    {
        ID: 1,
        NAME: 'Mr. XYZ',
        PURPOSE_OF_VISIT: 'Capmia Mens Chronograph Watch 44mm 5 ATM',
        MEETING_WITH_ID: 1,
        MEETING_WITH_NAME: 'ABC',
        DATE_OF_VISIT: '06-04-2023',
        DURATION_OF_VISIT: '01hrs 10m',
        DURATION_HRS: 2,
        DURATION_MINUTES: 10,
        COMPANY_NAME: 'X Industry',
        COUNTRY: 'India',
        CITY: 'Sangli',
        PROFESSION: 'MD',
        VISITOR_ID: 3,
        ACTIVE: false,
    },
];
