
export const events = [
    {
        ID: 1,
        FULLNAME: 'SK ash',
        EMAILID: 'skuser@gmail.com',
        COMPANY: 'SK Photographers',
        CONTACTNO: 9898989898,
        VISITEDON: "4/12/2023",
        CODE: '+91',
    },
    {
        ID: 2,
        FULLNAME: 'PK Photographers',
        EMAILID: 'pkuser@gmail.com',
        COMPANY: 'PK Photographers',
        CONTACTNO: 9898989898,
        VISITEDON: "7/12/2023",
        CODE: '+91',
    },
    {
        ID: 3,
        FULLNAME: 'Mr. XYZ',
        EMAILID: 'xyz@gmail.com',
        COMPANY: 'X Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "9/12/2023",
        CODE: '+91',
    },

    {
        ID: 4,
        FULLNAME: 'Mr. AAXYZ',
        EMAILID: 'sad@gmail.com',
        COMPANY: 'terryye Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "18/2/2022",
        CODE: '+91',
    },
    {
        ID: 5,
        FULLNAME: 'Mr. GGGXYZ',
        EMAILID: 'ahtj@gmail.com',
        COMPANY: 'Xee Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "2/12/2023",
        CODE: '+91',
    },
    {
        ID: 6,
        FULLNAME: 'SK Photographers',
        EMAILID: 'skuser@gmail.com',
        COMPANY: 'SK Photographers',
        CONTACTNO: 9898989898,
        VISITEDON: "4-12-2023",
        CODE: '+91',
    },
    {
        ID: 7,
        FULLNAME: 'PK Photographers',
        EMAILID: 'pkuser@gmail.com',
        COMPANY: 'PK Photographers',
        CONTACTNO: 9898989898,
        VISITEDON: "7-12-2023",
        CODE: '+91',
    },
    {
        ID: 8,
        FULLNAME: 'Mr. XYZ',
        EMAILID: 'xyz@gmail.com',
        COMPANY: 'X Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "9-12-2023",
        CODE: '+91',
    },

    {
        ID: 9,
        FULLNAME: 'Mr. AAXYZ',
        EMAILID: 'sad@gmail.com',
        COMPANY: 'terryye Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "10-12-2023",
        CODE: '+91',
    },
    {
        ID: 10,
        FULLNAME: 'Mr. GGGXYZ',
        EMAILID: 'ahtj@gmail.com',
        COMPANY: 'Xee Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "2-12-2023",
        CODE: '+91',
    }, {
        ID: 11,
        FULLNAME: 'SK Photographers',
        EMAILID: 'skuser@gmail.com',
        COMPANY: 'SK Photographers',
        CONTACTNO: 9898989898,
        VISITEDON: "4-12-2023",
        CODE: '+91',
    },
    {
        ID: 12,
        FULLNAME: 'PK Photographers',
        EMAILID: 'pkuser@gmail.com',
        COMPANY: 'PK Photographers',
        CONTACTNO: 9898989898,
        VISITEDON: "7-12-2023",
        CODE: '+91',
    },
    {
        ID: 13,
        FULLNAME: 'Mr. XYZ',
        EMAILID: 'xyz@gmail.com',
        COMPANY: 'X Industry',
        CONTACTNO: 9898989898,
        VISITEDON: "9-12-2023",
        CODE: '+91',
    },

    {
        ID: 14,
        FULLNAME: 'Mr. AAXYZ',
        EMAILID: 'sad@gmail.com',
        COMPANY: 'terryye Industry',
        CONTACTNO: 9898989898,
        VISITEDON: '31/05/2023',
        CODE: '+91',
    },
    {
        ID: 15,
        FULLNAME: 'Mr. GGGXYZ',
        EMAILID: 'ahtj@gmail.com',
        COMPANY: 'Xee Industry',
        CONTACTNO: 9898989898,
        VISITEDON: '2-12-2023',
        CODE: '+91',
    }
];



