export const Theme = [
    {
        ID: 1,
        NAME: 'Theme1',
        FONTFAMILY: 'Algerian',
        FONTSIZE: 12,
        PRIMARYCOLOR: 'Red',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#707070',
        selectedColor2:   '#707070',
        selectedColor3:   '#707070',
        background2light:   '#707070',
        background1dark:   '#707070',
        textcolor1:   '#707070',
        Textdark1:   '#707070',
        info1:  '#707070',
        warning1:  '#707070',
        d1:  '#707070',
        accentcolor: '#707070',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'Page-Level style',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'Page-Level style',
        CustomCss: 'External Styles'
    },
    {
        ID: 2,
        NAME: 'Theme2',
        FONTFAMILY: 'monospace',
        FONTSIZE: 12,
        PRIMARYCOLOR: 'green',
        SECONDARYCOLOR: 'Blue',
        
        selectedColor:'#da9595',
        selectedColor2:   '#da9595',
        selectedColor3:   '#da9595',
        background2light:   '#da9595',
        background1dark:   '#da9595',
        textcolor1:   '#da9595',
        Textdark1:   '#da9595',
        info1:  '#da9595',
        warning1:  '#da9595',
        d1:  '#da9595',
        accentcolor: '#da9595',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'External Styles'
        
    },
    {
        ID: 3,
        NAME: 'Theme1',
        FONTFAMILY: 'Algerian',
        FONTSIZE: 10,
        PRIMARYCOLOR: 'Red',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#781f1f',
        selectedColor2:   '#781f1f',
        selectedColor3:   '#781f1f',
        background2light:   '#781f1f',
        background1dark:   '#781f1f',
        textcolor1:   '#781f1f',
        Textdark1:   '#781f1f',
        info1:  '#781f1f',
        warning1:  '#781f1f',
        d1:  '#781f1f',
        accentcolor: '#781f1f',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'BUTTONSTYLE',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'BUTTONSTYLE'
    },
    {
        ID: 4,
        NAME: 'Theme2',
        FONTFAMILY: 'fantasy',
        FONTSIZE: 11,
        PRIMARYCOLOR: 'green',
        SECONDARYCOLOR: 'brown',
        selectedColor:'#662222',
        selectedColor2:   '#662222',
        selectedColor3:   '#662222',
        background2light:   '#662222',
        background1dark:   '#662222',
        textcolor1:   '#662222',
        Textdark1:   '#662222',
        info1:  '#662222',
        warning1:  '#662222',
        d1:  '#781f1f',
        accentcolor: '#781f1f',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'BUTTONSTYLE',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'BUTTONSTYLE'
    },
    {
        ID: 5,
        NAME: 'Theme3',
        FONTFAMILY: 'Algerian',
        FONTSIZE: 9,
        PRIMARYCOLOR: 'Red',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#707070',
        selectedColor2:   '#707070',
        selectedColor3:   '#707070',
        background2light:   '#707070',
        background1dark:   '#707070',
        textcolor1:   '#707070',
        Textdark1:   '#707070',
        info1:  '#707070',
        warning1:  '#707070',
        d1:  '#707070',
        accentcolor: '#707070',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'Page-Level style',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'Page-Level style',
        CustomCss: 'External Styles'
    },
    {
        ID: 6,
        NAME: 'Theme2',
        FONTFAMILY: 'monospace',
        FONTSIZE: 12,
        PRIMARYCOLOR: 'green',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#da9595',
        selectedColor2:   '#da9595',
        selectedColor3:   '#da9595',
        background2light:   '#da9595',
        background1dark:   '#da9595',
        textcolor1:   '#da9595',
        Textdark1:   '#da9595',
        info1:  '#da9595',
        warning1:  '#da9595',
        d1:  '#da9595',
        accentcolor: '#da9595',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'External Styles'
    },
    {
        ID: 7,
        NAME: 'Theme9',
        FONTFAMILY: 'Algerian',
        FONTSIZE: 10,
        PRIMARYCOLOR: 'Red',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#da9595',
        selectedColor2:   '#da9595',
        selectedColor3:   '#da9595',
        background2light:   '#da9595',
        background1dark:   '#da9595',
        textcolor1:   '#da9595',
        Textdark1:   '#da9595',
        info1:  '#da9595',
        warning1:  '#da9595',
        d1:  '#da9595',
        accentcolor: '#da9595',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'External Styles'
    },
    {
        ID: 8,
        NAME: 'Theme10',
        FONTFAMILY: 'fantasy',
        FONTSIZE: 11,
        PRIMARYCOLOR: 'green',
        SECONDARYCOLOR: 'brown',
        selectedColor:'#662222',
        selectedColor2:   '#662222',
        selectedColor3:   '#662222',
        background2light:   '#662222',
        background1dark:   '#662222',
        textcolor1:   '#662222',
        Textdark1:   '#662222',
        info1:  '#662222',
        warning1:  '#662222',
        d1:  '#781f1f',
        accentcolor: '#781f1f',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'BUTTONSTYLE',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'BUTTONSTYLE'
    },
    {
        ID: 9,
        NAME: 'Theme20',
        FONTFAMILY: 'Algerian',
        FONTSIZE: 0,
        PRIMARYCOLOR: 'Red',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#da9595',
        selectedColor2:   '#da9595',
        selectedColor3:   '#da9595',
        background2light:   '#da9595',
        background1dark:   '#da9595',
        textcolor1:   '#da9595',
        Textdark1:   '#da9595',
        info1:  '#da9595',
        warning1:  '#da9595',
        d1:  '#da9595',
        accentcolor: '#da9595',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'External Styles'
    },
    {
        ID: 10,
        NAME: 'Theme2',
        FONTFAMILY: 'monospace',
        FONTSIZE: 12,
        PRIMARYCOLOR: 'yellow',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#da9595',
        selectedColor2:   '#da9595',
        selectedColor3:   '#da9595',
        background2light:   '#da9595',
        background1dark:   '#da9595',
        textcolor1:   '#da9595',
        Textdark1:   '#da9595',
        info1:  '#da9595',
        warning1:  '#da9595',
        d1:  '#da9595',
        accentcolor: '#da9595',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'External Styles'
    },
    {
        ID: 11,
        NAME: 'Theme1',
        FONTFAMILY: 'Algerian',
        FONTSIZE: 10,
        PRIMARYCOLOR: 'Red',
        SECONDARYCOLOR: 'Blue',
        selectedColor:'#662222',
        selectedColor2:   '#662222',
        selectedColor3:   '#662222',
        background2light:   '#662222',
        background1dark:   '#662222',
        textcolor1:   '#662222',
        Textdark1:   '#662222',
        info1:  '#662222',
        warning1:  '#662222',
        d1:  '#781f1f',
        accentcolor: '#781f1f',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'BUTTONSTYLE',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'BUTTONSTYLE'
    },
    {
        ID: 12,
        NAME: 'Theme2',
        FONTFAMILY: 'cursive',
        FONTSIZE: 1,
        PRIMARYCOLOR: 'green',
        SECONDARYCOLOR: 'brown',
        selectedColor:'#da9595',
        selectedColor2:   '#da9595',
        selectedColor3:   '#da9595',
        background2light:   '#da9595',
        background1dark:   '#da9595',
        textcolor1:   '#da9595',
        Textdark1:   '#da9595',
        info1:  '#da9595',
        warning1:  '#da9595',
        d1:  '#da9595',
        accentcolor: '#da9595',
        BUTTONSTYLE: 'Local style',
        MANUSTYLE: 'MANUSTYLE',
        CUSTOMSTYLE: 'External Styles',
        LAYOUTSTYLE: 'MANUSTYLE',
        CustomCss: 'External Styles'
    },


    
  
];