export const sms = [
    
    {
        ID: 1,
        NAME: 'Aniket  Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth2',
        Body: 'xyz',

        primary: true,
    },
    {
        ID: 2,
        NAME: 'Abhishek Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth2',
        Body: 'xyz',
        primary: true,
    },
    {
        ID: 3,
        NAME: 'shubham Patil',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth',
        Body: 'xyz',
        primary: false,
    },
    {
        ID: 4,
        NAME: 'Rahul Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Password',
        Body: 'xyz',
        primary: true,
    },
    {
        ID: 5,
        NAME: 'Mohit Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Password',
        Body: 'xyz',

        primary: false,
    },
    {
        ID: 6,
        NAME: 'Aniket  Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Login',
        Body: 'xyz',

        primary: true,
    },
    {
        ID: 7,
        NAME: 'Abhishek Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth2',
        Body: 'xyz',
        primary: true,
    },
    {
        ID: 8,
        NAME: 'shubham Patil',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth',
        Body: 'xyz',
        primary: false,
    },
    {
        ID: 9,
        NAME: 'Rahul Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Password',
        Body: 'xyz',
        primary: true,
    },
    {
        ID: 10,
        NAME: 'Mohit Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Password',
        Body: 'xyz',

        primary: false,
    },
    {
        ID: 11,
        NAME: 'Aniket  Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Login',
        Body: 'xyz',

        primary: true,
    },
    {
        ID: 12,
        NAME: 'Abhishek Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Plain',
        Body: 'xyz',
        primary: true,
    },
    {
        ID: 13,
        NAME: 'shubham Patil',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth',
        Body: 'xyz',
        primary: false,
    },
    {
        ID: 14,
        NAME: 'Rahul Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'Plain',
        Body: 'xyz',
        primary: true,
    },
    {
        ID: 15,
        NAME: 'Mohit Ganapati Gurav',
        BaseUrl: 'aptefoods.com',
        AuthenticationHeader: 'abc',
        Method: 'XOAuth2',
        Body: 'xyz',

        primary: false,
    },
];