export const floors = [
    {
        ID: 1,
        NAME: 'floor1',
        LOCATION: 'string',
        LENGTH: 12,
        WIDTH: 23,
        HEIGHT: 23,
        LENGTH_UNIT: 'F',
        WIDTH_UNIT: 'F',
        HEIGHT_UNIT: 'F',
    },
    {
        ID: 2,
        NAME: 'floor1',
        LOCATION: 'string',
        LENGTH: 12,
        WIDTH: 23,
        HEIGHT: 23,
        LENGTH_UNIT: 'F',
        WIDTH_UNIT: 'F',
        HEIGHT_UNIT: 'F',
    },
    {
        ID: 3,
        NAME: 'floor1',
        LOCATION: 'string',
        LENGTH: 12,
        WIDTH: 23,
        HEIGHT: 23,
        LENGTH_UNIT: 'F',
        WIDTH_UNIT: 'F',
        HEIGHT_UNIT: 'F',
    },

    {
        ID: 4,
        NAME: 'floor1',
        LOCATION: 'string',
        LENGTH: 12,
        WIDTH: 23,
        HEIGHT: 23,
        LENGTH_UNIT: 'F',
        WIDTH_UNIT: 'F',
        HEIGHT_UNIT: 'F',
    },
    {
        ID: 5,
        NAME: 'floor1',
        LOCATION: 'string',
        LENGTH: 12,
        WIDTH: 23,
        HEIGHT: 23,
        LENGTH_UNIT: 'F',
        WIDTH_UNIT: 'F',
        HEIGHT_UNIT: 'F',
    },
];
